version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started

  backend:
    build: ./server
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://user:password@db:5432/farmhealth_db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: farmhealth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d farmhealth_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
